name: Deploy Hook

on:
    push:
        branches:
            - main
        paths:
            - "landing-page/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Make a GET request to deploy hook
              run: curl -X GET ${{secrets.API_DEPLOY_HOOK}}
